spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./data/h2db_2;Mode=Oracle;AUTO_SERVER=TRUE
    username: sa
    password: sa

server:
  port: 8090